# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
