# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_products_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default='Product description.'),
        ),
    ]
