# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_products_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_url',
            field=models.TextField(default='123'),
        ),
    ]
