# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 13:18
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='SN',
        ),
        migrations.AddField(
            model_name='orders',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(related_name='ordered_products', to='cart.Products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
