# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20171211_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='billing_method',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_method',
            field=models.CharField(default='', max_length=30),
        ),
    ]
