export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'

export const SET_SHIPPING_OPTIONS = 'SET_SHIPPING_OPTIONS'
export const CLEAR_SHIPPING_OPTIONS = 'CLEAR_SHIPPING_OPTIONS'

export const SET_BILLING_OPTIONS = 'SET_BILLING_OPTIONS'
export const CLEAR_BILLING_OPTIONS = 'CLEAR_BILLING_OPTIONS'
